version: '3.8'

services:
  redis-master:
    image: library/redis:6.0.6-alpine
    ports:
      - 6379:6379
    volumes:
      - ./:/data

  jaeger-allinone:
    image: jaegertracing/all-in-one:1.18.1
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411