server:
  port: 8082

app:
  name: redis-service

# Fluentd
logging:
  config: "classpath:logback-spring.xml"
  fluentd:
    host: localhost
    port: 24224

# Redis
spring:
  redis:
    key: USER2
    host: localhost
    port: 6379

# Jaeger
opentracing:
  jaeger:
    service-name: redis-service
    enabled: true
    udp-sender:
        host: localhost
        port: 6831

# Spring-actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always