server:
  port: 8081

app:
  name: client-service

redis:
  client:
    host: http://redis-service:8082/users

opentracing:
  jaeger:
    service-name: client-service
    enabled: true
    udp-sender:
      host: jaeger-allinone
      port: 6831

logging:
  config: "classpath:logback-spring.xml"
  fluentd:
    host: fluentd
    port: 24224

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always