server:
  port: 8081

redis:
  client:
    host: http://localhost:8082/users

opentracing:
  jaeger:
    service-name: client-service
    enabled: true
    udp-sender:
      host: localhost
      port: 6831

logging:
  fluentd:
    host: localhost
    port: 24224

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always